'use strict'
angular = require 'angular'
d3 = require 'd3'
app = angular.module 'mainApp', [require 'angular-material']
	.directive 'gridDer', require './components/grid/grid'
	.directive 'circleDer', require './components/grid/circle'
	# .
	# .directive 'horAxisDer', require './directives/xAxis'
	# .directive 'verAxisDer', require './directives/yAxis'
	# .directive 'cartSimDer', require './components/cart/cartSim'
	# .directive 'cartObjectDer', require './components/cart/cartObject'
	.directive 'shifter' , require './directives/shifter'
	# .directive 'behavior', require './directives/behavior'
	# .directive 'dotADer', require './components/design/dotA'
	# .directive 'dotBDer', require './components/design/dotB'
	# .directive 'datum', require './directives/datum'
	# .directive 'd3Der', require './directives/d3Der'
	# .directive 'designADer', require './components/design/designA'
	# .directive 'designBDer' , require './components/design/designB'
	# .directive 'derivativeADer', require './components/derivative/derivativeA'
	# .directive 'derivativeBDer', require './components/derivative/derivativeB'
	# .directive 'cartPlotDer', require './components/cart/cartPlot'
	# .directive 'designCartADer', require './components/design/designCartA'
	# .directive 'designCartBDer', require './components/design/designCartB'
	# .directive 'textureDer', require './directives/texture'
	# .directive 'boilerplateDer', require './directives/boilerplate'
	# .directive 'cartDer' , require './directives/cartDer'
	# .service 'derivativeData', require './components/derivative/derivativeData'
	# .service 'fakeCart', require './components/design/fakeCart'
	# .service 'trueCart', require './components/design/trueCart'
	# .service 'designData', require './components/design/designData'
	# .service 'cartData', require './components/cart/cartData'

